<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:34px 38px}body{font-family:DejaVu Sans,sans-serif;color:#152128;font-size:10px;line-height:1.5}.cover{background:#07324A;color:#fff;padding:28px;border-radius:10px;margin-bottom:20px}.brand{font-size:11px;letter-spacing:2px;color:#F0C24C}.cover h1{font-size:25px;margin:20px 0 6px}.cover p{font-size:12px;color:#EAF1F5}.pill{display:inline-block;background:#FCF5E3;color:#07324A;padding:4px 9px;border-radius:12px;margin:2px}h2{font-size:16px;color:#07324A;border-bottom:2px solid #DDA822;padding-bottom:5px;margin-top:20px}.box{background:#EAF1F5;border-left:4px solid #07324A;padding:10px 12px;margin:10px 0}.warning{background:#FCF5E3;border-left-color:#DDA822}table{width:100%;border-collapse:collapse;margin:8px 0 16px}th{background:#07324A;color:#fff;text-align:left;padding:7px}td{border:1px solid #D8E0E9;padding:6px;vertical-align:top}tr:nth-child(even) td{background:#F5F7FA}.req{color:#CA2B2B;font-weight:bold}.opt{color:#2C9664;font-weight:bold}.page{page-break-before:always}.footer{position:fixed;bottom:-22px;right:0;color:#4F6672;font-size:8px}
</style></head><body><div class="footer">ALEF DELTA · Employee Import Standard · {{ now()->format('Y-m-d') }}</div>
<div class="cover"><div class="brand">ALEF DELTA ERP</div><h1>Employee Excel &amp; CSV Import</h1><p>Reusable template, Ethiopian/Gregorian dates, safe create/update matching, column-level validation, and account creation.</p></div>
<div><span class="pill">XLSX</span><span class="pill">XLS</span><span class="pill">CSV</span><span class="pill">EC + GC</span><span class="pill">Safe row processing</span></div>
<h2>Quick workflow</h2><table><tr><th>Step</th><th>Action</th></tr><tr><td>1</td><td>Open <b>employee_import_template.xlsx</b>. Do not rename its headers.</td></tr><tr><td>2</td><td>Enter one employee per row. Keep phone cells as text so leading zeroes are preserved.</td></tr><tr><td>3</td><td>On Employees, choose <b>Import Excel</b>, select the default category and calendar, then upload.</td></tr><tr><td>4</td><td>Review CREATED, UPDATED, UNCHANGED, and ERROR for every row. Correct only failed rows and upload again.</td></tr></table>
<div class="box"><b>Legacy workbook support:</b> Files containing <b>Name</b>, <b>Phone</b>, and <b>Hired Date</b> are accepted. A combined name is split at its first space.</div>
<h2>Field reference</h2><table><tr><th style="width:20%">Column</th><th style="width:12%">Rule</th><th>Description</th></tr>
@foreach([
['employee_code','Optional','Recommended when updating an employee. It permits a safe phone change and must match an existing Employee ID. Leave blank for new employees.'],
['first_name','Required','Employee given name. A legacy combined Name column may be used instead.'],
['last_name','Optional','Family/remaining names. If omitted, the importer stores a placeholder because the current employee record requires it.'],
['email','Optional','Must be a valid, unique email. A private ERP login email is generated when blank.'],
['phone_number','Required','09XXXXXXXX or +2519XXXXXXXX. Local format is stored as +251 automatically. Must be unique.'],
['status','Optional','ACTIVE, PROBATION, INACTIVE, or TERMINATED. Defaults to ACTIVE.'],
['category','Optional','Exact category name/code/ID. A blank cell uses the category selected in the upload window.'],
['hire_date','Optional','EC: DD/MM/YYYY or DD/MM/YY. GC: YYYY-MM-DD or DD/MM/YYYY. Excel date cells are accepted. Blank uses the import date.'],
['date_calendar','Optional','EC or GC. A blank cell uses the calendar selected in the upload window.']
] as $field)<tr><td><b>{{ $field[0] }}</b></td><td class="{{ $field[1]==='Required'?'req':'opt' }}">{{ $field[1] }}</td><td>{{ $field[2] }}</td></tr>@endforeach</table>
<div class="page"></div><h2>Date rules</h2><table><tr><th>Calendar</th><th>Examples</th><th>Stored value</th></tr><tr><td><b>EC</b></td><td>10/01/2016, 10/01/16, and month 13 dates such as 04/13/2018.</td><td>Validated and converted to the equivalent Gregorian database date.</td></tr><tr><td><b>GC</b></td><td>2026-09-21 or 21/09/2026.</td><td>Stored as the same Gregorian business date.</td></tr></table>
<h2>Results and update safety</h2><div class="box"><b>CREATED:</b> Employee and member login account were created.<br><b>UPDATED:</b> An existing employee was found and only changed supplied fields were saved; the password was preserved.<br><b>UNCHANGED:</b> The employee exists and supplied values are identical.<br><b>ERROR:</b> Only that row is rejected and the exact column/value is reported. Other valid rows continue.<br><b>EMPTY:</b> Blank rows are ignored.</div>
<h2>Login credentials</h2><p>The result table shows the generated Employee ID and initial password. The rule is <b>Employee ID-last four phone digits</b>, for example <b>EMP00123-4567</b>. The employee should change it after first login.</p>
<h2>Common errors</h2><table><tr><th>Message</th><th>Resolution</th></tr><tr><td>Missing required columns</td><td>Use the standard template or the supported Name/Phone legacy headers.</td></tr><tr><td>Invalid Ethiopian mobile number</td><td>Use exactly 09 plus eight digits, or +2519 plus eight digits.</td></tr><tr><td>Category was not found</td><td>Choose a category from Jobs → Manage Categories or use the upload-window default.</td></tr><tr><td>Invalid EC date</td><td>Check day/month order. EC months 1–12 have 30 days; Pagume is month 13.</td></tr></table>
<div class="warning box"><b>Important:</b> Keep the row result report until all errors are corrected. Re-uploading is safe: matching rows are updated only when supplied values changed, otherwise they are reported as UNCHANGED.</div></body></html>
