<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:34px 38px}body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:10px;line-height:1.45}.cover{background:#123b73;color:#fff;padding:28px;border-radius:10px;margin-bottom:22px}.brand{font-size:11px;letter-spacing:2px}.cover h1{font-size:25px;margin:22px 0 6px}.cover p{font-size:12px;color:#dbeafe}.pill{display:inline-block;background:#e8f1ff;color:#123b73;padding:4px 9px;border-radius:12px;margin:2px}h2{font-size:16px;color:#123b73;border-bottom:2px solid #dbeafe;padding-bottom:5px;margin-top:20px}h3{font-size:12px;color:#1d4f91}.box{background:#f4f7fb;border-left:4px solid #2f6fbb;padding:10px 12px;margin:10px 0}.warning{background:#fff7e6;border-left-color:#e39a17}table{width:100%;border-collapse:collapse;margin:8px 0 16px}th{background:#123b73;color:#fff;text-align:left;padding:7px}td{border:1px solid #d7dfeb;padding:6px;vertical-align:top}tr:nth-child(even) td{background:#f8fafc}.req{color:#b42318;font-weight:bold}.opt{color:#39734c;font-weight:bold}.page{page-break-before:always}.footer{position:fixed;bottom:-22px;right:0;color:#718096;font-size:8px}
</style></head><body><div class="footer">ALEF DELTA · Attendance Import Standard · {{ now()->format('Y-m-d') }}</div>
<div class="cover"><div class="brand">ALEF DELTA ERP</div><h1>Attendance Excel Import</h1><p>Standard data template, validation rules, GPS requirements, safe updates, and troubleshooting.</p></div>
<div><span class="pill">MANUAL</span><span class="pill">GPS</span><span class="pill">MIXED</span><span class="pill">Row-level validation</span><span class="pill">Safe update</span></div>
<h2>Quick workflow</h2><table><tr><th>Step</th><th>Action</th></tr><tr><td>1</td><td>Open <b>attendance_import_template.xlsx</b>. Keep the header names unchanged.</td></tr><tr><td>2</td><td>Enter one employee shift per row. Use the built-in dropdowns for status and attendance type.</td></tr><tr><td>3</td><td>Upload from Attendance → Manual Entry → Excel Import.</td></tr><tr><td>4</td><td>Review CREATED, UPDATED, UNCHANGED, and ERROR results for every row. Correct only failed rows and upload again.</td></tr></table>
<div class="box"><b>Employee matching:</b> Always use the exact Employee ID from the Employees page, for example <b>EMP001</b> or <b>FS-000013</b>. Names are not used because they can be duplicated.</div>
<h2>Field reference</h2><table><tr><th style="width:19%">Column</th><th style="width:9%">Rule</th><th>Description and accepted format</th></tr>
@foreach([
['employee_code','Required','Exact employee ID/code. Case-insensitive.'],['attendance_date','Required','Attendance business date: YYYY-MM-DD. Excel date cells are accepted.'],['status','Required','Use the dropdown: PRESENT, LATE, LATE_WITH_PERMISSION, ABSENT, ABSENT_WITH_PERMISSION, POLICY_VIOLATION.'],['attendance_type','Required','MANUAL, GPS, or MIXED.'],['clock_in_time','Optional','HH:MM, HH:MM:SS, full date/time, or Excel time. Defaults to shift start for non-absent rows.'],['clock_out_time','Optional','Same formats as clock-in. Defaults to shift end. Must not be earlier than clock-in.'],['site_id','Optional','Useful when the employee has multiple shifts on the same date. Must match the scheduled site.'],['schedule_id','Optional','Best option for exact shift matching. Takes priority with employee/date validation.'],['clock_in_latitude','GPS required','Decimal -90 to 90. Required for non-absent GPS rows.'],['clock_in_longitude','GPS required','Decimal -180 to 180. Required for non-absent GPS rows.'],['clock_in_accuracy_m','Optional','Device accuracy in metres; zero or greater.'],['clock_out_latitude','Optional','Decimal -90 to 90. Used to verify clock-out location.'],['clock_out_longitude','Optional','Decimal -180 to 180. Used to verify clock-out location.'],['clock_out_accuracy_m','Optional','Clock-out device accuracy in metres.'],['note','Conditional','Optional up to 500 characters; required for POLICY_VIOLATION.']
] as $f)<tr><td><b>{{ $f[0] }}</b></td><td class="{{ $f[1]==='Required'?'req':'opt' }}">{{ $f[1] }}</td><td>{{ $f[2] }}</td></tr>@endforeach</table>
<div class="page"></div><h2>Attendance types and GPS behavior</h2><table><tr><th>Type</th><th>Use</th><th>Verification</th></tr><tr><td><b>MANUAL</b></td><td>Paper register, supervisor entry, or office-prepared attendance.</td><td>Coordinates are ignored; record is marked as manually verified.</td></tr><tr><td><b>GPS</b></td><td>Imported device/GPS data.</td><td>Clock-in coordinates are required and checked against the scheduled site's GPS radius.</td></tr><tr><td><b>MIXED</b></td><td>Manual record with optional GPS evidence.</td><td>When coordinates exist they are checked against the site; otherwise the record remains a manual decision.</td></tr></table>
<h2>Status rules</h2><table><tr><th>Status</th><th>Meaning</th></tr><tr><td>PRESENT</td><td>Attended normally.</td></tr><tr><td>LATE</td><td>Late without permission.</td></tr><tr><td>LATE_WITH_PERMISSION</td><td>Late with approved permission.</td></tr><tr><td>ABSENT</td><td>Absent without permission; times and GPS are not required.</td></tr><tr><td>ABSENT_WITH_PERMISSION</td><td>Approved absence.</td></tr><tr><td>POLICY_VIOLATION</td><td>Attended but violated a rule, such as uniform requirements. A note is mandatory.</td></tr></table>
<h2>Duplicates and safe updates</h2><div class="box"><b>UNCHANGED:</b> An attendance record already exists and every imported value is the same.<br><b>UPDATED:</b> A record exists but one or more spreadsheet values changed; only that attendance record is updated.<br><b>CREATED:</b> No attendance exists for the matched shift.<br><b>ERROR:</b> The row is rejected and rolled back. Other rows continue.</div>
<h2>Common errors</h2><table><tr><th>Message</th><th>How to fix it</th></tr><tr><td>Employee ID was not found</td><td>Copy the exact employee code from Employees.</td></tr><tr><td>No scheduled shift found</td><td>Create the roster shift first, or correct the date/site/schedule ID.</td></tr><tr><td>Multiple shifts found</td><td>Add site_id or schedule_id.</td></tr><tr><td>Missing required columns</td><td>Use the standard workbook and do not rename headers.</td></tr><tr><td>GPS coordinates required/outside range</td><td>Provide valid decimal latitude and longitude for GPS rows.</td></tr></table>
<div class="warning box"><b>Important:</b> Keep the result report until all ERROR rows are corrected. Re-uploading is safe: unchanged records are not duplicated.</div></body></html>
