<!doctype html><html><head><meta charset="utf-8"><style>
@font-face{font-family:NotoEthiopic;src:url('{{ public_path('fonts/NotoSansEthiopic-Regular.ttf') }}') format('truetype');font-weight:400}@font-face{font-family:NotoEthiopic;src:url('{{ public_path('fonts/NotoSansEthiopic-Bold.ttf') }}') format('truetype');font-weight:700}@page{margin:34px 38px}body{font-family:NotoEthiopic,DejaVu Sans,sans-serif;color:#172033;font-size:10px;line-height:1.55}.cover{background:#123b73;color:#fff;padding:28px;border-radius:10px;margin-bottom:22px}.brand{font-size:11px;letter-spacing:2px}.cover h1{font-size:24px;margin:22px 0 6px}.cover p{font-size:12px;color:#dbeafe}.pill{display:inline-block;background:#e8f1ff;color:#123b73;padding:4px 9px;border-radius:12px;margin:2px}h2{font-size:16px;color:#123b73;border-bottom:2px solid #dbeafe;padding-bottom:5px;margin-top:20px}.box{background:#f4f7fb;border-left:4px solid #2f6fbb;padding:10px 12px;margin:10px 0}.warning{background:#fff7e6;border-left-color:#e39a17}table{width:100%;border-collapse:collapse;margin:8px 0 16px}th{background:#123b73;color:#fff;text-align:left;padding:7px}td{border:1px solid #d7dfeb;padding:6px;vertical-align:top}tr:nth-child(even) td{background:#f8fafc}.req{color:#b42318;font-weight:bold}.opt{color:#39734c;font-weight:bold}.page{page-break-before:always}.footer{position:fixed;bottom:-22px;right:0;color:#718096;font-size:8px}
</style></head><body><div class="footer">ALEF DELTA · የአቴንዳንስ ኢምፖርት መመሪያ · {{ now()->format('Y-m-d') }}</div>
<div class="cover"><div class="brand">ALEF DELTA ERP</div><h1>የአቴንዳንስ Excel ኢምፖርት</h1><p>መደበኛ የውሂብ ቅጽ፣ የማረጋገጫ ሕጎች፣ የGPS መስፈርቶች፣ ደህንነቱ የተጠበቀ ማዘመን እና የስህተት መፍትሔ።</p></div>
<div><span class="pill">MANUAL</span><span class="pill">GPS</span><span class="pill">MIXED</span><span class="pill">በእያንዳንዱ ረድፍ ማረጋገጫ</span></div>
<h2>ፈጣን የአጠቃቀም ደረጃዎች</h2><table><tr><th>ደረጃ</th><th>ተግባር</th></tr><tr><td>1</td><td><b>attendance_import_template.xlsx</b> ይክፈቱ። የአምዶቹን ስም አይቀይሩ።</td></tr><tr><td>2</td><td>በእያንዳንዱ ረድፍ የአንድ ሠራተኛ የአንድ ሺፍት አቴንዳንስ ያስገቡ። status እና attendance_type ከdropdown ይምረጡ።</td></tr><tr><td>3</td><td>Attendance → Manual Entry → Excel Import በመግባት ፋይሉን ይጫኑ።</td></tr><tr><td>4</td><td>CREATED፣ UPDATED፣ UNCHANGED እና ERROR ውጤቶችን ይመልከቱ። ስህተት ያለባቸውን ረድፎች ብቻ አርሙና እንደገና ይጫኑ።</td></tr></table>
<div class="box"><b>ሠራተኛን ለማዛመድ፦</b> በEmployees ገጽ ላይ ያለውን ትክክለኛ Employee ID ይጠቀሙ፣ ለምሳሌ <b>EMP001</b> ወይም <b>FS-000013</b>። ስሞች ሊደጋገሙ ስለሚችሉ ለማዛመድ አይጠቀሙም።</div>
<h2>የእያንዳንዱ አምድ መመሪያ</h2><table><tr><th style="width:19%">አምድ</th><th style="width:12%">መስፈርት</th><th>መግለጫ እና ቅርጸት</th></tr>
@foreach([
['employee_code','ግዴታ','ትክክለኛ Employee ID/code።'],['attendance_date','ግዴታ','የአቴንዳንስ ቀን YYYY-MM-DD። የExcel date cell ይቀበላል።'],['status','ግዴታ','ከdropdown ይምረጡ፦ PRESENT, LATE, LATE_WITH_PERMISSION, ABSENT, ABSENT_WITH_PERMISSION, POLICY_VIOLATION።'],['attendance_type','ግዴታ','MANUAL፣ GPS ወይም MIXED።'],['clock_in_time','አማራጭ','HH:MM፣ HH:MM:SS፣ ሙሉ date/time ወይም Excel time። ካልተሞላ የሺፍት መግቢያ ሰዓት ይጠቀማል።'],['clock_out_time','አማራጭ','እንደ clock-in ተመሳሳይ ቅርጸት። ከclock-in በፊት መሆን የለበትም።'],['site_id','አማራጭ','ሠራተኛው በአንድ ቀን ብዙ ሺፍት ካለው ትክክለኛውን ሳይት ለመምረጥ።'],['schedule_id','አማራጭ','ትክክለኛውን ሺፍት ለመለየት በጣም የሚመከር።'],['clock_in_latitude','GPS ግዴታ','ከ -90 እስከ 90። ለGPS መግቢያ ያስፈልጋል።'],['clock_in_longitude','GPS ግዴታ','ከ -180 እስከ 180። ለGPS መግቢያ ያስፈልጋል።'],['clock_in_accuracy_m','አማራጭ','የመሣሪያው ትክክለኛነት በሜትር።'],['clock_out_latitude','አማራጭ','የመውጫ latitude።'],['clock_out_longitude','አማራጭ','የመውጫ longitude።'],['clock_out_accuracy_m','አማራጭ','የመውጫ GPS ትክክለኛነት በሜትር።'],['note','እንደሁኔታው','እስከ 500 ፊደል። ለPOLICY_VIOLATION ግዴታ ነው።']
] as $f)<tr><td><b>{{ $f[0] }}</b></td><td class="{{ $f[1]==='ግዴታ'?'req':'opt' }}">{{ $f[1] }}</td><td>{{ $f[2] }}</td></tr>@endforeach</table>
<div class="page"></div><h2>የአቴንዳንስ ዓይነቶች እና GPS</h2><table><tr><th>ዓይነት</th><th>አጠቃቀም</th><th>ማረጋገጫ</th></tr><tr><td><b>MANUAL</b></td><td>የወረቀት መዝገብ፣ የሱፐርቫይዘር ወይም የቢሮ ግብዓት።</td><td>GPS መረጃ አይፈለግም፤ በእጅ እንደተረጋገጠ ይመዘገባል።</td></tr><tr><td><b>GPS</b></td><td>ከGPS መሣሪያ የመጣ ውሂብ።</td><td>የመግቢያ latitude/longitude ግዴታ ሲሆን ከሳይቱ radius ጋር ይረጋገጣል።</td></tr><tr><td><b>MIXED</b></td><td>በእጅ የተሞላ መዝገብ ከአማራጭ GPS ማስረጃ ጋር።</td><td>GPS ካለ ከሳይቱ radius ጋር ይረጋገጣል።</td></tr></table>
<h2>የStatus ትርጉም</h2><table><tr><th>Status</th><th>ትርጉም</th></tr><tr><td>PRESENT</td><td>በመደበኛው ተገኝቷል።</td></tr><tr><td>LATE</td><td>ያለፈቃድ ዘግይቷል።</td></tr><tr><td>LATE_WITH_PERMISSION</td><td>በፈቃድ ዘግይቷል።</td></tr><tr><td>ABSENT</td><td>ያለፈቃድ ቀርቷል።</td></tr><tr><td>ABSENT_WITH_PERMISSION</td><td>በፈቃድ ቀርቷል።</td></tr><tr><td>POLICY_VIOLATION</td><td>ተገኝቶ ሕግ አልተከተለም፣ ለምሳሌ ዩኒፎርም። note ግዴታ ነው።</td></tr></table>
<h2>የተደጋጋሚ መረጃ እና ደህንነቱ የተጠበቀ ማዘመን</h2><div class="box"><b>UNCHANGED፦</b> መዝገቡ አለ እና ሁሉም መረጃ ተመሳሳይ ነው።<br><b>UPDATED፦</b> መዝገቡ አለ ነገር ግን አንድ ወይም ከዚያ በላይ መረጃ ተቀይሯል።<br><b>CREATED፦</b> አዲስ መዝገብ ተፈጥሯል።<br><b>ERROR፦</b> ያ ረድፍ አልገባም፤ ሌሎች ትክክለኛ ረድፎች ግን ይቀጥላሉ።</div>
<h2>የተለመዱ ስህተቶች</h2><table><tr><th>መልዕክት</th><th>መፍትሔ</th></tr><tr><td>Employee ID was not found</td><td>ከEmployees ገጽ ትክክለኛውን employee code ይቅዱ።</td></tr><tr><td>No scheduled shift found</td><td>መጀመሪያ roster shift ይፍጠሩ ወይም date/site/schedule ID ያርሙ።</td></tr><tr><td>Multiple shifts found</td><td>site_id ወይም schedule_id ያስገቡ።</td></tr><tr><td>Missing required columns</td><td>መደበኛውን Excel ቅጽ ይጠቀሙ፤ header አይቀይሩ።</td></tr></table>
<div class="warning box"><b>አስፈላጊ፦</b> ሁሉም ERROR ረድፎች እስኪስተካከሉ የውጤት ሪፖርቱን ያስቀምጡ። እንደገና መጫን ደህና ነው፤ ተመሳሳይ መረጃ አይደገምም።</div></body></html>
