<!doctype html><html><head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;font-size:9px;color:#1f2937}h1{font-size:18px;margin:0 0 4px}.muted{color:#6b7280}.cards{width:100%;margin:14px 0;border-collapse:separate;border-spacing:5px}.cards td{border:1px solid #d1d5db;padding:8px;background:#f8fafc}.value{font-size:16px;font-weight:bold}h2{font-size:13px;margin:16px 0 6px}table.data{width:100%;border-collapse:collapse}.data th,.data td{border:1px solid #d1d5db;padding:5px;text-align:left}.data th{background:#e5e7eb}.page-break{page-break-before:always}.right{text-align:right}.bad{color:#dc2626}.good{color:#059669}
</style></head><body>
<h1>Clients, Sites and Payments Report</h1><div class="muted">Period: {{ $startDate ?: 'All' }} to {{ $endDate ?: 'All' }} · Generated {{ now()->format('Y-m-d H:i') }}</div>
<table class="cards"><tr>@foreach(['clients'=>'Clients','sites'=>'Sites','employees'=>'Employees','field_staff'=>'Field Staff','paid'=>'Paid','overdue'=>'Overdue','verified'=>'Verified','on_time'=>'On Time'] as $key=>$label)<td><div class="muted">{{ $label }}</div><div class="value">{{ $report['summary'][$key] }}</div></td>@endforeach</tr></table>
<h2>Client Summary</h2><table class="data"><thead><tr><th>Company</th><th>Sites</th><th>Invoices</th><th>Billed</th><th>Paid</th><th>Due</th><th>Overdue</th><th>Verified</th><th>On Time</th><th>Paid Late</th></tr></thead><tbody>@foreach($report['clients'] as $row)<tr><td>{{ $row['company'] }}</td><td>{{ $row['sites'] }}</td><td>{{ $row['invoices'] }}</td><td>ETB {{ number_format($row['total_billed'],2) }}</td><td>{{ $row['paid'] }}</td><td>{{ $row['next_due_date'] ?: '—' }}</td><td class="bad">{{ $row['overdue'] }}</td><td>{{ $row['verified'] }}</td><td class="good">{{ $row['on_time'] }}</td><td>{{ $row['paid_late'] }}</td></tr>@endforeach</tbody></table>
<h2>Site Staffing</h2><table class="data"><thead><tr><th>Company</th><th>Site</th><th>Employees</th><th>Field Staff</th><th>Total</th><th>GPS Radius</th></tr></thead><tbody>@foreach($report['staff_by_site'] as $row)<tr><td>{{ $row['company'] }}</td><td>{{ $row['site'] }}</td><td>{{ $row['employees'] }}</td><td>{{ $row['field_staff'] }}</td><td>{{ $row['total_staff'] }}</td><td>{{ $row['gps_radius'] }} m</td></tr>@endforeach</tbody></table>
<div class="page-break"></div><h2>Invoice and Payment Detail</h2><table class="data"><thead><tr><th>Invoice</th><th>Company</th><th>Invoice Date</th><th>Due Date</th><th>Payment Date</th><th>Amount</th><th>Status</th><th>Verified</th><th>Timing</th></tr></thead><tbody>@foreach($report['invoices'] as $row)<tr><td>{{ $row['invoice_number'] }}</td><td>{{ $row['company'] }}</td><td>{{ $row['invoice_date'] }}</td><td>{{ $row['due_date'] }}</td><td>{{ $row['payment_date'] ?: '—' }}</td><td>ETB {{ number_format($row['amount'],2) }}</td><td>{{ $row['status'] }}</td><td>{{ $row['verified'] ? 'Yes':'No' }}</td><td>{{ $row['on_time'] ? 'On time' : ($row['paid_late'] ? 'Paid late' : ($row['overdue'] ? 'Overdue':'Due')) }}</td></tr>@endforeach</tbody></table>
</body></html>
